// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package player

import "strconv"

type Color int8

const (
	ColorRed    Color = 0
	ColorGreen  Color = 1
	ColorBlue   Color = 2
	ColorYellow Color = 3
	ColorPink   Color = 4
	ColorGray   Color = 5
	ColorOrange Color = 6
)

var EnumNamesColor = map[Color]string{
	ColorRed:    "Red",
	ColorGreen:  "Green",
	ColorBlue:   "Blue",
	ColorYellow: "Yellow",
	ColorPink:   "Pink",
	ColorGray:   "Gray",
	ColorOrange: "Orange",
}

var EnumValuesColor = map[string]Color{
	"Red":    ColorRed,
	"Green":  ColorGreen,
	"Blue":   ColorBlue,
	"Yellow": ColorYellow,
	"Pink":   ColorPink,
	"Gray":   ColorGray,
	"Orange": ColorOrange,
}

func (v Color) String() string {
	if s, ok := EnumNamesColor[v]; ok {
		return s
	}
	return "Color(" + strconv.FormatInt(int64(v), 10) + ")"
}
