// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package player

import "strconv"

type UpdateMsg int8

const (
	UpdateMsglogin  UpdateMsg = 0
	UpdateMsglogout UpdateMsg = 1
	UpdateMsgsync   UpdateMsg = 2
)

var EnumNamesUpdateMsg = map[UpdateMsg]string{
	UpdateMsglogin:  "login",
	UpdateMsglogout: "logout",
	UpdateMsgsync:   "sync",
}

var EnumValuesUpdateMsg = map[string]UpdateMsg{
	"login":  UpdateMsglogin,
	"logout": UpdateMsglogout,
	"sync":   UpdateMsgsync,
}

func (v UpdateMsg) String() string {
	if s, ok := EnumNamesUpdateMsg[v]; ok {
		return s
	}
	return "UpdateMsg(" + strconv.FormatInt(int64(v), 10) + ")"
}
